[supervisord]
nodaemon=true                      ; stay in the foreground so Docker can track this as PID 1
user=root

[program:sshd]
command=/usr/sbin/sshd -D -e       ; same flags the base image uses as its own entrypoint
autostart=true
autorestart=true
priority=10

; Notice the lack of user, we run as root, nginx will drop to www-data
; Nginx master process bounces to bg, and forks processes into the fg. This will screw up supervisord if we
; don't force the master branch to the fg
[program:nginx]
command=/usr/sbin/nginx -g 'daemon off;'
autostart=true
autorestart=true
priority=20
stopsignal=QUIT ; nginx graceful shutdown is QUIT, not INT
