---
- name: Create TLS directory
  ansible.builtin.file:
    path: /etc/nginx/tls
    state: directory
    mode: "0755"

- name: Generate Private Key
  community.crypto.openssl_privatekey:
    path: /etc/nginx/tls/localhost.key
    type: RSA
    size: 2048
    mode: "0600"

- name: Generate 1 CSR for multiple domains
  community.crypto.openssl_csr:
    path: /etc/nginx/tls/localhost.csr
    privatekey_path: /etc/nginx/tls/localhost.key # see generate private key above
    common_name: localhost
    subject_alt_name:
      - "DNS:localhost"
      - "DNS:*.localhost"
      - "IP:127.0.0.1"
    mode: "0644"

- name: Use CSR to generate a self-signed certificate
  community.crypto.x509_certificate:
    path: /etc/nginx/tls/localhost.crt
    privatekey_path: /etc/nginx/tls/localhost.key
    csr_path: /etc/nginx/tls/localhost.csr
    provider: selfsigned
    selfsigned_not_after: "+3650d"
    mode: "0644"
  notify: listen for reload nginx