[supervisord]
nodaemon=true                      ; stay in the foreground so Docker can track this as PID 1
user=root

[program:sshd]
command=/usr/sbin/sshd -D -e       ; same flags the base image uses as its own entrypoint
autostart=true
autorestart=true
priority=10

; Apache 2 is all sorts of weird in how you have to boot it, especially foreground mode
[program:apache2]
command=/usr/sbin/apache2ctl -D FOREGROUND
autostart=true
autorestart=true
stopsignnal=WINCH ; Apache's graceful-stop signal in foreground mode
; we want docker logs, not apache logs
stdout_logfile=/dev/stdout_logfile
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=20

